using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace Web.Composition.DesignTime
{
	public class AutoGeneratedMigrationsGenerator(MigrationsCodeGeneratorDependencies dependencies, CSharpMigrationsGeneratorDependencies csharpDependencies) : CSharpMigrationsGenerator(dependencies, csharpDependencies)
	{
		private readonly string header = "// <auto-generated />";

		public override string GenerateMigration(string? migrationNamespace, string migrationName, IReadOnlyList<MigrationOperation> upOperations, IReadOnlyList<MigrationOperation> downOperations)
		{
			// Add <auto-generated> header so code quality systems will ignore the generated migration classes
			return header + Environment.NewLine + base.GenerateMigration(migrationNamespace, migrationName, upOperations, downOperations);
		}
	}
}
