using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Migrations.Design;

namespace Web.Composition.DesignTime
{
	public class VerdantDesignTimeServices : IDesignTimeServices
	{
		public void ConfigureDesignTimeServices(IServiceCollection services)
		{
			services.AddSingleton<IMigrationsCodeGenerator, AutoGeneratedMigrationsGenerator>();
		}
	}
}
