// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Data.Migrations
{
    /// <inheritdoc />
    public partial class DomainRefactor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserRegistrations");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserPlants",
                table: "UserPlants");

            migrationBuilder.DropIndex(
                name: "IX_UserPlants_UserId",
                table: "UserPlants");

            migrationBuilder.DropColumn(
                name: "LastWateredDate",
                table: "Plants");

            migrationBuilder.DropColumn(
                name: "SummerWateringInterval",
                table: "Plants");

            migrationBuilder.DropColumn(
                name: "WinterWateringInterval",
                table: "Plants");

            migrationBuilder.RenameColumn(
                name: "ScientificName",
                table: "Plants",
                newName: "Name_ScientificName");

            migrationBuilder.RenameColumn(
                name: "GivenName",
                table: "Plants",
                newName: "Name_GivenName");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserPlants",
                table: "UserPlants",
                columns: new[] { "UserId", "PlantId" });

            migrationBuilder.CreateIndex(
                name: "IX_UserPlants_PlantId",
                table: "UserPlants",
                column: "PlantId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_UserPlants",
                table: "UserPlants");

            migrationBuilder.DropIndex(
                name: "IX_UserPlants_PlantId",
                table: "UserPlants");

            migrationBuilder.RenameColumn(
                name: "Name_ScientificName",
                table: "Plants",
                newName: "ScientificName");

            migrationBuilder.RenameColumn(
                name: "Name_GivenName",
                table: "Plants",
                newName: "GivenName");

            migrationBuilder.AddColumn<DateTime>(
                name: "LastWateredDate",
                table: "Plants",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "SummerWateringInterval",
                table: "Plants",
                type: "bigint",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddColumn<long>(
                name: "WinterWateringInterval",
                table: "Plants",
                type: "bigint",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserPlants",
                table: "UserPlants",
                columns: new[] { "PlantId", "UserId" });

            migrationBuilder.CreateTable(
                name: "UserRegistrations",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ExpirationDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Token = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserRegistrations", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserPlants_UserId",
                table: "UserPlants",
                column: "UserId");
        }
    }
}
