using Data.Generators;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.Extensions.DependencyInjection;

namespace Data
{
	public class VerdantDesignTimeServices : IDesignTimeServices
	{
		public void ConfigureDesignTimeServices(IServiceCollection services)
		{
			services.AddSingleton<IMigrationsCodeGenerator, AutoGeneratedMigrationsGenerator>();
		}
	}
}
